# Generated by Django 3.0.3 on 2020-04-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0002_auto_20200417_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='user',
        ),
    ]
