# Generated by Django 3.0.3 on 2020-04-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0006_employeeinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='user',
        ),
    ]
