# Generated by Django 3.0.3 on 2020-04-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_auto_20200409_2349'),
        ('FACERECOG', '0007_remove_employeeinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USERS.Profile'),
        ),
    ]
