# Generated by Django 3.0.3 on 2020-04-24 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0008_employeeinfo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
