# Generated by Django 3.0.3 on 2020-06-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0009_employeeinfo_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='profile',
        ),
    ]
