# Generated by Django 3.0.3 on 2020-06-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FACERECOG', '0010_remove_employeeinfo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='usr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
