# Generated by Django 3.0.3 on 2020-06-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0011_employeeinfo_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='usr',
        ),
    ]
