# Generated by Django 3.0.3 on 2020-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0012_remove_employeeinfo_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memname', models.CharField(blank=True, max_length=30, null=True)),
                ('memimage', models.ImageField(default='default.jpg', upload_to='aboutmember_pics')),
            ],
        ),
    ]
