# Generated by Django 3.0.3 on 2020-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0013_aboutemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutemployees',
            name='memimage',
            field=models.ImageField(default='default.jpg', upload_to='aboutmember_pics/'),
        ),
    ]
