# Generated by Django 3.0.3 on 2020-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACERECOG', '0014_auto_20200612_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutemployees',
            name='memimage',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
